version: "3.8"

services:
  domain-api:
    build:
      context: ./services/domain-service
      dockerfile: Dockerfile
    ports:
      - 6868:8080
    networks:
      - kiosk-net
    volumes:
      - kiosk-res

networks:
  kiosk-net:
volumes:
  kiosk-res:
