version: "3.8"

services:
  mysql-service:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=ratm
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql